services:
  - type: web
    name: resulynx
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn resulynx.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resulynx.settings
