# Generated by Django 5.2.4 on 2025-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('skills', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
    ]
